- name: Gather Cisco ASA facts with basic SSH
  ansible.netcommon.cli_command:
    command: "show version"
  register: asa_version_output
  delegate_to: "{{ item.value.ansible_host }}"
  vars:
    ansible_user: "{{ item.value.ansible_user }}"
    ansible_ssh_pass: "{{ item.value.ansible_ssh_pass }}"
  ignore_errors: yes

- name: Extract Serial Number from version output
  set_fact:
    device_serial_number: "{{ asa_version_output.stdout | regex_search('Serial Number: (\\S+)', '\\1') | first }}"
  when: asa_version_output is defined
