- name: Execute command to get hardware inventory for Viptela
  ansible.builtin.command:
    cmd: "show hardware inventory Chassis serial-number"
  vars:
    ansible_connection: network_cli
    ansible_network_os: viptela
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  register: hardware_inventory_output
  ignore_errors: yes

- name: Parse serial number from hardware inventory
  set_fact:
    device_serial_number: "{{ hardware_inventory_output.stdout | regex_search('Chassis\\s+0\\s+(\\S+)', '\\1') }}"
  when: hardware_inventory_output.stdout is defined
