---
# Run mnap scans

- name: Remove files from previous run
  ansible.builtin.file:
    path: "{{ nmap_output_dir }}"
    state: absent


- name: Create output directory
  ansible.builtin.file:
    path: "{{ nmap_output_dir }}"
    state: directory
    mode: '0755'

- name: Execute nmap scans
  ansible.builtin.command: /usr/bin/python3 {{ role_path }}/files/nmap_2.py
  register: output
