---
# Run mnap scans

- name: create output directory
  file:
    path: "{{ nmap_output_dir }}"
    state: directory
    mode: '0755'

- name: execute nmap scans
  command: ./nmap_2.py
  args:
    chdir: "{{ role_path }}"/files
  register: output