---
# Run mnap scans

- name: create output directory
  file:
    path: "{{ nmap_output_dir }}"
    state: directory
    mode: '0755'

- name: execute nmap scans
  script: nmap_2.py
  register: result
