---
# Run mnap scans

- name: create output directory
  file:
    path: "{{ nmap_output_dir }}"
    state: directory
    mode: '0755'

- name: execute nmap scans
  ansible.builtin.command:
    argv:
      - /usr/bin/python3 {{ lookup('file', 'nmap_2.py') }}
  register: result
