---
# Run mnap scans

- name: create output directory
  file:
    path: "{{ nmap_output_dir }}"
    state: directory
    mode: '0755'

- name: execute nmap scans
  command: /usr/bin/python3 {{ role_path }}/files/nmap_2.py
  register: output
