---
# Run mnap scans

- name: create output directory
  file:
    path: "{{ nmap_output_dir }}"
    state: directory
    mode: '0755'

- name: execute nmap scans
  ansible.builtin.command:
    agrv:
      - /usr/bin/python3 nmap_2.py
  register: result
