---
# Run mnap scans

- name: create output directory
  file:
    path: "{{ nmap_output_dir }}"
    state: directory
    mode: '0755'

- name: execute nmap scans
<<<<<<<<< Temporary merge branch 1
  command: ./nmap_2.py
  args:
    chdir: "{{ role_path }}"/files
  register: output
=========
  ansible.builtin.command:
    argv:
      - cd {{ role_path }}/files
      - /usr/bin/python3 nmap_2.py
  register: result
